#!/bin/sh
#
# sshd	Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

umask 077

start() {
	# Create any missing keys
	/usr/bin/ssh-keygen -A

	echo \"start sshd ......\"
	chown root:root -R /var/empty/
	chown root:root -R /root/
	chmod 755 -R /root
	chown root:root /root/.ssh/authorized_keys
	chmod 600 /root/.ssh/authorized_keys
	chmod 755 /var/empty/
	echo \"sshd:x:74:74:Privilege-separated SSH:/var/empty/sshd:/sbin/nologin\" >>/etc/passwd
	printf "Starting sshd: "
	/usr/sbin/sshd
	touch /var/lock/sshd
	ifconfig eth0 10.0.2.15 netmask 255.255.255.0
	route add default gw 10.0.2.2
	export TIMEOUTFACTOR=600
	echo "OK"
}
stop() {
	printf "Stopping sshd: "
	killall sshd
	rm -f /var/lock/sshd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
