#!/bin/bash

#grep "test_1" $1 > /dev/null
#if [ $? -ne 0 ]; then
#	echo "csky-ci tests failed: perf failed"
#        return 1
#fi
#grep "test_2" $1 > /dev/null
#if [ $? -ne 0 ]; then
#        echo "csky-ci tests failed: perf failed"
#        return 1
#fi
#grep "test_3" $1 > /dev/null
#if [ $? -ne 0 ]; then
#        echo "csky-ci tests failed: perf failed"
#        return 1
#fi
#grep "test_4" $1 > /dev/null
#if [ $? -ne 0 ]; then
#        echo "csky-ci tests failed: perf failed"
#        return 1
#fi
echo "perf test pass"
