#!/bin/sh
echo "***** start init for csky test ****"
mount -a
mount -t tmpfs tmpfs /tmp
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
ifconfig lo 127.0.0.1

ifconfig eth0 172.16.150.110 netmask 255.255.255.0
route add default gw 172.16.150.254
sleep 10
[ ! -d /home/rtos_nfs ] && mkdir -p /home/rtos_nfs
#mount -t nfs 192.168.0.41:/newdata/home/rtos_nfs /home/rtos_nfs -o nolock,tcp
mount -t nfs 192.168.0.41:/newdata/home/rtos_nfs /home/rtos_nfs -o nolock,tcp
[ ! -d /magic_nfs ]  && mkdir -p /magic_nfs
#mount -t nfs 192.168.0.57:/magic_nfs /magic_nfs -o nolock,tcp
mount -o remount,rw /home/rtos_nfs
chmod 777 /dev/null
chmod 755 /dev/urandom

