CIRCUSTENT_VERSION = 45811c2bb2c7e4d91bde3305479eae5b325184ff
CIRCUSTENT_SITE = $(call github,tactcomplabs,circustent,$(CIRCUSTENT_VERSION))
CIRCUSTENT_LICENSE = Apache-2.0
CIRCUSTENT_LICENSE_FILES = LICENSE
CIRCUSTENT_CONF_OPTS = \
		-DENABLE_PTHREADS=ON

$(eval $(cmake-package))

