#!/bin/sh

echo "rcS"
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

#
# To enable telnetd
#
/usr/sbin/telnetd

#
# To config network
#
# ifconfig eth0 up
# ifconfig eth0 172.16.150.120 netmask 255.255.255.0
# route add default gw 172.16.150.254

#
# To mount NFS
#
# mkdir -p /mnt/nfs
# mount -t nfs 172.16.28.159:/home/ztw/work/nfs_share  /mnt/nfs  -o nolock,tcp,sync
